/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: filechunk.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "filechunk.pb-c.h"
void   file_chunk__init
                     (FileChunk         *message)
{
  static const FileChunk init_value = FILE_CHUNK__INIT;
  *message = init_value;
}
size_t file_chunk__get_packed_size
                     (const FileChunk *message)
{
  assert(message->base.descriptor == &file_chunk__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t file_chunk__pack
                     (const FileChunk *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &file_chunk__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t file_chunk__pack_to_buffer
                     (const FileChunk *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &file_chunk__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FileChunk *
       file_chunk__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FileChunk *)
     protobuf_c_message_unpack (&file_chunk__descriptor,
                                allocator, len, data);
}
void   file_chunk__free_unpacked
                     (FileChunk *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &file_chunk__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor file_chunk__field_descriptors[5] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FileChunk, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filename",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FileChunk, filename),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(FileChunk, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FileChunk, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_size",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FileChunk, total_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned file_chunk__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = filename */
  3,   /* field[3] = size */
  4,   /* field[4] = total_size */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange file_chunk__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor file_chunk__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FileChunk",
  "FileChunk",
  "FileChunk",
  "",
  sizeof(FileChunk),
  5,
  file_chunk__field_descriptors,
  file_chunk__field_indices_by_name,
  1,  file_chunk__number_ranges,
  (ProtobufCMessageInit) file_chunk__init,
  NULL,NULL,NULL    /* reserved[123] */
};
