/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: filechunk.proto */

#ifndef PROTOBUF_C_filechunk_2eproto__INCLUDED
#define PROTOBUF_C_filechunk_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct FileChunk FileChunk;


/* --- enums --- */


/* --- messages --- */

struct  FileChunk
{
  ProtobufCMessage base;
  char *version;
  char *filename;
  ProtobufCBinaryData data;
  int32_t size;
  int32_t total_size;
};
#define FILE_CHUNK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&file_chunk__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, {0,NULL}, 0, 0 }


/* FileChunk methods */
void   file_chunk__init
                     (FileChunk         *message);
size_t file_chunk__get_packed_size
                     (const FileChunk   *message);
size_t file_chunk__pack
                     (const FileChunk   *message,
                      uint8_t             *out);
size_t file_chunk__pack_to_buffer
                     (const FileChunk   *message,
                      ProtobufCBuffer     *buffer);
FileChunk *
       file_chunk__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   file_chunk__free_unpacked
                     (FileChunk *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*FileChunk_Closure)
                 (const FileChunk *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor file_chunk__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_filechunk_2eproto__INCLUDED */
